version: '3.8'

services:
  # Servicio de base de datos MariaDB
  mariadb:
    image: mariadb:10.6
    container_name: notificaciones-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: notificaciones_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - notificaciones-network

  # Servicio de phpMyAdmin (opcional, para administrar la base de datos)
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: notificaciones-phpmyadmin
  #   restart: always
  #   environment:
  #     PMA_HOST: mariadb
  #     PMA_PORT: 3306
  #     MYSQL_ROOT_PASSWORD: password
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - notificaciones-network

  # Tu microservicio de notificaciones
  notificaciones-ms:
    build: .
    container_name: notificaciones-ms
    restart: always
    environment:
      NODE_ENV: development
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: notificaciones_db
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
    ports:
      - '3000:3000'
    depends_on:
      - mariadb
    networks:
      - notificaciones-network

networks:
  notificaciones-network:
    driver: bridge

volumes:
  mariadb_data:
